export const env = {
  CLERK_PUBLISHABLE_KEY: import.meta.env.VITE_CLERK_PUBLISHABLE_KEY,
  MIKROTIK_API_URL: import.meta.env.VITE_MIKROTIK_API_URL,
  MIKROTIK_API_KEY: import.meta.env.VITE_MIKROTIK_API_KEY,
  WHATSAPP_API_URL: import.meta.env.VITE_WHATSAPP_API_URL,
  WHATSAPP_API_KEY: import.meta.env.VITE_WHATSAPP_API_KEY,
  WHATSAPP_GROUP_ID: import.meta.env.VITE_WHATSAPP_GROUP_ID,
};